/* eslint-disable @next/next/no-page-custom-font */
import Navbar from '@/components/Navbar';
import '@/styles/globals.css';
import type { AppProps } from 'next/app';
import Head from 'next/head';
import PageLayout from './PageLayout';

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      {/* create <NextPageWithLaoyout/> */}
      <Head>
        <title>Yatri Energy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Barlow:wght@400;500;600&display=swap" rel="stylesheet" />
      </Head>
      {/* create div with spacing */}

      <div className="m-2">
        <Navbar />
        <Component {...pageProps} />
      </div>

      {/* <PageLayout>
        <Navbar />
      </PageLayout> */}
    </>
  );
}
